#!/usr/bin/env python
"""assetsmd.py -- ASSETS.md: every picture job and video clip the film has, with what it's for. Regenerate any time.

    python tools/assetsmd.py

Pictures: every job in tools/jobs/*.json (grouped by job file), plus any assets/gen/<job>/ no job file lists; each with
its seeds on disk, whether it is cut out or used whole (film.json nocutPrefixes / whole, the same rule as
tools/cutout.py), and the prompt's gist. Clips: every list in film.json clipLists (notes/clips/clips.json), with its
moment, frames on disk and whether they are upscaled (a clip folder holding .raw is still CPU frames).
"""
import glob
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from film import FILM, ROOT  # noqa: E402

GEN = os.path.join(ROOT, 'assets', 'gen')
NOCUT = lambda j: j.startswith(tuple(FILM.get('nocutPrefixes', []))) or j in set(FILM.get('whole', []))


def gist(p, n=150):
    p = re.sub(r'<lora:[^>]+>\s*', '', p or '')                      # LoRA tags
    p = re.sub(r'@\w+\.\s*', '', p)                                    # artist tags
    p = re.sub(r'\b(masterpiece|best quality|high quality|highres|absurdres|newest|very aesthetic)\b,?\s*', '', p)
    return (p[:n] + '...') if len(p) > n else p


def seeds_on_disk(job):
    return sorted(os.path.basename(f)[:-4] for f in glob.glob(os.path.join(GEN, job, '*.png')) if not os.path.basename(f).startswith('_'))


def main():
    out = [f"# ASSETS: every picture and video clip in {FILM.get('title', FILM['name'])}",
           '(generated by tools/assetsmd.py: do not edit; regenerate after a batch)', '']
    listed = set()
    for jf in sorted(glob.glob(os.path.join(ROOT, 'tools', 'jobs', '*.json'))):
        try:
            jobs = json.load(open(jf, encoding='utf-8'))
        except Exception as e:
            out += [f'## {os.path.basename(jf)}: unreadable ({e})', '']
            continue
        out += [f'## tools/jobs/{os.path.basename(jf)}', '', '| job | seeds on disk | use | prompt |', '|---|---|---|---|']
        for j in jobs if isinstance(jobs, list) else [jobs]:
            n = j.get('job', '?')
            listed.add(n)
            out.append(f"| {n} | {' '.join(seeds_on_disk(n)) or '-'} | {'whole' if NOCUT(n) else 'cut'} | {gist(j.get('prompt')).replace('|', '/')} |")
        out.append('')
    extra = sorted(d for d in os.listdir(GEN) if os.path.isdir(os.path.join(GEN, d)) and d not in listed) if os.path.isdir(GEN) else []
    if extra:
        out += ['## in assets/gen but in no job file', '', '| job | seeds on disk | use |', '|---|---|---|']
        out += [f"| {n} | {' '.join(seeds_on_disk(n))} | {'whole' if NOCUT(n) else 'cut'} |" for n in extra] + ['']
    for lf in FILM.get('clipLists', []):
        p = os.path.join(ROOT, lf)
        if not os.path.exists(p):
            continue
        out += [f'## clips: {lf}', '', '| clip | moment | frames | state |', '|---|---|---|---|']
        for c in json.load(open(p, encoding='utf-8')):
            d = os.path.join(ROOT, 'assets', 'clips', c['name'])
            nf = len(glob.glob(os.path.join(d, '*.jpg'))) if os.path.isdir(d) else 0
            state = 'no frames yet' if not nf else ('CPU frames (.raw)' if os.path.exists(os.path.join(d, '.raw')) else 'upscaled')
            out.append(f"| {c['name']} | {str(c.get('moment', '')).replace('|', '/')} | {nf} | {state} |")
        out.append('')
    open(os.path.join(ROOT, 'ASSETS.md'), 'w', encoding='utf-8').write('\n'.join(out) + '\n')
    print(f'ASSETS.md: {len(listed) + len(extra)} picture jobs')


if __name__ == '__main__':
    main()
