#!/usr/bin/env python
"""clipsjs.py -- assets/clips/clips.js (window.DT_CLIPS = {name: {n, w, h}}) from the clip frame folders.
Run after a clip's frames change (tools/rawframes.py and tools/upscale.py run it themselves):  python tools/clipsjs.py"""
import json
import os

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__))).replace(os.sep, '/')
D = f'{ROOT}/assets/clips'
out = {}
for name in sorted(os.listdir(D)):
    p = f'{D}/{name}'
    if not os.path.isdir(p):
        continue
    fr = sorted(f for f in os.listdir(p) if f.endswith('.jpg'))
    if not fr:
        continue
    w, h = Image.open(f'{p}/{fr[0]}').size
    out[name] = {'n': len(fr), 'w': w, 'h': h}
# KEYED clips (assets/clipa/<name>/: alpha PNG frames, tools/keyclip.py) get their own table, so a scene can test for them
A = f'{ROOT}/assets/clipa'
keyed = {}
for name in sorted(os.listdir(A)) if os.path.isdir(A) else []:
    p = f'{A}/{name}'
    fr = sorted(f for f in os.listdir(p) if f.endswith('.png')) if os.path.isdir(p) else []
    if fr:
        w, h = Image.open(f'{p}/{fr[0]}').size
        # the FIGURE's box (alpha > 140, union over every frame), so K.meta can size and feet-anchor a keyed clip like a
        # cut-out (standing a figure on a clip frame's full box used to float the feet)
        import numpy as np
        x0 = y0 = 10 ** 9; x1 = y1 = -1
        for f in fr:
            a = np.asarray(Image.open(f'{p}/{f}'))[..., 3] > 140
            ys, xs = np.where(a)
            if len(xs):
                x0, y0, x1, y1 = min(x0, int(xs.min())), min(y0, int(ys.min())), max(x1, int(xs.max()) + 1), max(y1, int(ys.max()) + 1)
        keyed[name] = {'n': len(fr), 'w': w, 'h': h, 'bbox': [x0, y0, x1, y1] if x1 > 0 else [0, 0, w, h]}
with open(f'{D}/clips.js', 'w', encoding='utf-8') as f:
    f.write('// generated by tools/clipsjs.py -- do not edit. Video clips as JPG frames: clip:<name>/<frame>\n')
    f.write('window.DT_CLIPS = ' + json.dumps(out, indent=0).replace('\n', '') + ';\n')
    f.write('window.DT_CLIPA = ' + json.dumps(keyed) + ";   // keyed clips (alpha): 'clipa:<name>/<frame>'" + chr(10))
print(len(out), 'clips ->', f'{D}/clips.js')
