#!/usr/bin/env python
"""timing.py -- song/timing.json + web/timing.js: everything the engine reads about the song.

    <PY> song/timing.py
    (PY = the kit's python: `python tools/film.py PY` prints its path)

Reads song/reading.json (song/analyze.py: the drum-attack grid: bpm, beat 0, the downbeat phase) and song/sections.json
(the measured section map, TIMES ONLY: {"sections": [{"id", "bars": "0-7", "t0", "t1", "story"?}], "stops": [...]}),
and writes: bpm, beat0, barOffset (B<n> = beat 4n + barOffset: the bar anchors timeline.js and render.mjs --from B7
use), duration, sections (with this film's story per section), kicks / snares (time lists), accents [[t, strength 0..1,
'd'|'o']] (local-normalised drum + 'other' onsets: impact frames go there), vox [[start, end]] (vocal phrase TIMES
only), stops, per-frame envelopes (rms/low/mid/high/onset/voc at 24 fps), and lines = [] (NO LYRICS: a commercial
song's words never reach a painter; the raw transcript stays in song/private/).
Until song/sections.json exists, the whole song is one section ('all'), with a warning."""
import json
import os
import re
import sys

import librosa
import numpy as np
import soundfile as sf

HERE = os.path.dirname(os.path.abspath(__file__)).replace(os.sep, '/')
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, 'tools'))
from film import FILM  # noqa: E402

FPS = 24

# the film's story per section (STORYBOARD.md), keyed by sections.json id; a section's own "story" field wins.
# e.g. 'intro': 'R1: drums only, every hit is a flash of the city', 'stop1': 'R4: silence, one drop of colour'
STORY = {}


def env_curves(dur):
    x, sr = sf.read(f'{HERE}/audio.wav', dtype='float32', always_2d=True)
    y = x.mean(1)
    v, _ = sf.read(f'{HERE}/stems/vocals.wav', dtype='float32', always_2d=True)
    v = v.mean(1)
    hop = sr // FPS
    n = int(dur * FPS) + 2

    def rms(sig):
        out = np.zeros(n)
        for i in range(n):
            s = sig[i * hop:(i + 1) * hop]
            out[i] = np.sqrt(np.mean(s ** 2)) if len(s) else 0
        return out
    S = np.abs(librosa.stft(y, n_fft=2048, hop_length=hop))
    f = librosa.fft_frequencies(sr=sr, n_fft=2048)
    band = lambda lo, hi: S[(f >= lo) & (f < hi)].sum(0)
    low, mid, high = band(20, 200), band(200, 2000), band(2000, 12000)
    on = librosa.onset.onset_strength(y=y, sr=sr, hop_length=hop)

    def norm(a):
        a = np.asarray(a, float)[:n]
        a = np.pad(a, (0, max(0, n - len(a))))
        return [round(float(z), 3) for z in np.clip(a / (np.percentile(a, 99) + 1e-9), 0, 1)]
    return dict(fps=FPS, rms=norm(rms(y)), low=norm(low), mid=norm(mid), high=norm(high), onset=norm(on), voc=norm(rms(v)))


def main():
    R = json.load(open(f'{HERE}/reading.json', encoding='utf-8'))
    if os.path.exists(f'{HERE}/sections.json'):
        M = json.load(open(f'{HERE}/sections.json', encoding='utf-8'))
    else:
        print('WARNING: no song/sections.json yet: the whole song is one section. Measure the sections and rerun.')
        M = {'sections': [{'id': 'all', 'bars': '0', 't0': 0.0, 't1': R['duration']}], 'stops': R.get('stops', [])}
    bpm, beat0, dur = R['bpm'], R['beat0'], R['duration']
    dur = round(dur + float(FILM.get('holdAfter', 0)), 3)   # film.json holdAfter: seconds the film runs on past the song
    P = 60 / bpm
    secs = []
    for i, s in enumerate(M['sections']):
        # "bars": "0-7" / "12" / "-1-0" (a pickup before bar 0): the first number, sign included
        m = re.match(r'\s*(-?\d+(?:\.\d+)?)', str(s.get('bars', '0')))
        b = float(m.group(1)) if m else 0.0
        secs.append(dict(i=i, name=s['id'], bar=b, start=s['t0'], end=s['t1'], story=s.get('story') or STORY.get(s['id'], '')))
    stops = M.get('stops', [])
    off = R['downbeat_phase']
    out = dict(
        song=FILM.get('song', ''), duration=dur, bpm=bpm, beat0=beat0,
        barOffset=off, barLen=round(4 * P, 5),
        note=f'bar n = beat0 + (4n + {off}) beats = {beat0 + off * P:.4f} + {4 * P:.4f} n (B<n> anchors). Grid fitted on '
             'the drum stem attacks. NO LYRICS anywhere: vox = vocal phrase TIMES only.',
        sections=secs,
        beats=[round(b, 4) for b in R['beats']],
        kicks=[k for k, s in R['kicks'] if s >= 0.35],
        snares=[k for k, s in R['snares'] if s >= 0.35],
        accents=R['accents'],
        vox=R['vocal_phrases'],
        stops=stops,
        bars=[dict(bar=r['bar'], t=r['t'], mix=r['mix'], drums=r['drums'], vox=r['vox'], vcov=r['vcov']) for r in R['bars']],
        lines=[],
        env=env_curves(dur),
    )
    json.dump(out, open(f'{HERE}/timing.json', 'w', encoding='utf-8'))
    os.makedirs(f'{ROOT}/web', exist_ok=True)
    with open(f'{ROOT}/web/timing.js', 'w', encoding='utf-8') as fh:
        fh.write('// generated by song/timing.py -- do not edit (NO LYRICS: times only)\n')
        fh.write('window.DT_TIMING = ' + json.dumps(out) + ';\n')
    print(f'{bpm:.4f} BPM, beat0 {beat0}, bar {4 * P:.5f} s, {len(out["beats"])} beats, {len(out["kicks"])} kicks, '
          f'{len(out["snares"])} snares, {len(out["accents"])} accents, {len(out["vox"])} vocal phrases')
    for s in secs:
        print(f"  {s['name']:8s} B{s['bar']:<5} {s['start']:7.3f} - {s['end']:7.3f}  ({s['end'] - s['start']:5.2f} s)")


if __name__ == '__main__':
    main()
